- Stem-ecosystem.md
This pull requests adds a rough idea for the "reasons for wanting this project" section of the project bid. Feel free to leave comments for changes!
> Reasons bid update

- Stem-ecosystem.md
Added project scope and bio of me
> Updated document with project scope and bio of me

- Stem-ecosystem.md
I also made some changes to the Project Scope --------
What I liked  -----------
* Mentioning different user roles and FERPA, how the app will be maintainable
What I changed -------- 
* Changed the wording a little bit . ('different' user interface/features for each role, makes it seem like we need to include canvas.com-like functionality (student vs teacher view), which will both be hard and time-consuming). I'm going with 'alternative user interface/features'
* Added the user metrics requirement, event tagging and open-sourcing, Netflix-like functionality
> Added my bio and added/modified Project Scope and 

- README.md
Simply adds my thoughts on the executive summary portion of the project proposal.
> Add executive summary for project proposal

- README.md
> Updated project risk list

- README.md
Added risk to the risk list and updated resources needed.
> Updated document with risk list

- requirements.txt
CVE: https://bugzilla.redhat.com/show_bug.cgi?id=1663722
> Update django because v2.1.5 had a security vulnerability

- CODE-STYLE.md
This PR should close #35. We want to determine the important pieces for code style to keep things consistent. It's especially important since we're passing this off to somebody else at the end of the semester.
> Add project style guide

- README.md
The goal of this PR is to create a discussion around our technical plan for milestone 1. Feel free to leave comments and suggestions so we can talk about what we do/don't like!
[Here's a link to the rubric for convenience.](https://github.com/MLHale/CYBR4580-8950/blob/master/projects/milestone1.md#project-methodology)
> Add technical plan to milestone 1

- src/frontend/angular.json
- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/app/app.module.ts
- src/frontend/src/app/register/register.component.html
- src/frontend/src/app/register/register.component.scss
- src/frontend/src/app/register/register.component.ts
- src/frontend/src/app/register/register.service.spec.ts
- src/frontend/src/app/register/register.service.ts
- src/frontend/src/index.html
- src/frontend/src/main.ts
- src/frontend/src/styles.scss
Fixes problem with install of material in the Angular project
Updates made to user registration
> Fixes problem with material install.  Updates registration

- SETUP.md
I realized I missed some pieces in the `docker-compose` setup so I added some of those steps!
> Adding some missed setup pieces

- src/app/admin.py
- src/app/controllers/organization_controller.py
- src/app/models/__init__.py
- src/app/models/event.py
- src/app/models/user.py
- src/app/serializers/organization_serializer.py
- src/app/tests.py
- src/stem/urls.py
I derped pretty hard and completely missed adding the `organization` model to the API. This fixed that mistake!
This PR also updates all relative imports so they're more explicit.
> General cleanup

- src/frontend/src/app/app.module.ts
- src/frontend/src/app/components/event/event.component.scss
- src/frontend/src/app/components/register/register.component.html
- src/frontend/src/app/components/register/registerterms/registerterms.component.html
- src/frontend/src/app/components/register/registerterms/registerterms.component.spec.ts
- src/frontend/src/app/components/register/registerterms/registerterms.component.ts
Fixes missing terms of use component and changes size of cards on events
> Fixed terms of use and changed card size on events

- src/frontend/src/app/app-routing.module.ts
- src/frontend/src/app/app.module.ts
- src/frontend/src/app/components/event-add/event-add.component.html
- src/frontend/src/app/components/event-add/event-add.component.scss
- src/frontend/src/app/components/event-add/event-add.component.spec.ts
- src/frontend/src/app/components/event-add/event-add.component.ts
- src/frontend/src/app/components/home/home.component.html
- src/frontend/src/app/components/layout/header/header.component.html
This PR closes #56 by doing the following:
- Adds a button to reach the event creation form
- Adds form for event creation
What I need help with is figuring out the Angular structure. I'm not totally sure if a new component is needed for this or not. I'm used to grouping like components (`event` in this case) which handles all CRUD operations. The tutorials I found splits these up so I went that route with this feature. I'm completely open for whatever is going to work best!
> Add create event button

- Project-Progress.md
Added the project overview and current progress of the project. This completes the ticket #114
Any changes to the documentation are appreciated @codykaup and @jfranco1701
> Project progress milestone 2

- Project-Progress.md
Added completed functionality tickets in the outcome. This closes the ticket #115
> Updated Project progress with the Outcomes

- Project-Progress.md
Added some adjustments based on Joe's recommendations and Cory's PR: https://github.com/jfranco1701/STEM-Capstone-2019/pull/132
> Milestone 2 progress update

- src/frontend/src/app/app.module.ts
- src/frontend/src/app/components/profile/profile-child-add/profile-child-add.component.ts
- src/frontend/src/app/components/register/register.component.ts
Fixes a few issues from the merge.
> fix issues from merge

- src/frontend/src/app/components/profile/profile-child-add/profile-child-add.component.ts
- src/frontend/src/app/services/authentication.service.ts
- src/frontend/src/app/services/event-service.service.ts
- src/frontend/src/app/services/user.service.ts
- src/frontend/src/environments/environment.ts
This PR closes #149 by abstracting URLs to the environment file. This is required for the best prod deployment experience.
> Pull out hardcoded URLs into the environment file

- SETUP-PROD.md
- src/frontend/angular.json
- src/frontend/src/environments/environment.prod.ts
This PR officially closes #168. I got production setup and running so we have a decent workflow to work from when we're ready to deploy! 🎉
> Deploy to prod2

- docker-compose-prod.yml
- src/stem/settings.py
This PR closes #184 by dynamically updating Django `DEBUG` mode in dev/prod.
> Dynamically update debug mode

- src/frontend/src/app/components/profile/profile-child-add/profile-child-add.component.ts
I decided to look at that issue with creating child accounts that we were talking about. Turns out, I messed up the URL when I pulled everything into the environments file.. :(
When I looked at the request, it was responding yelling about the parent ID field being wrong. It definitely was wrong.
> Fix child creation issue

- prod/nginx/nginx.conf
I saw some fun issues when testing a new prod deploy. This fixes the nginx config so the urls do what you expect.
> Fix nginx config for production

- src/app/controllers/organization_controller.py
- src/app/controllers/user_controller.py
As discussed, we should limit user and organization view access based on the authenticated user. This does that! 🎉
> Limit API access

- src/frontend/package-lock.json
- src/frontend/src/app/components/layout/header/header.component.html
- src/frontend/src/app/components/layout/header/header.component.ts
If User is a student, cannot see the option of adding new events and parents profile. Student user can only see his profile and the events list. This closes the ticket #57
> User logged in as a student cannot add new events

- src/app/controllers/event_controller.py
- src/app/managers/event_manager.py
- src/app/serializers/user_serializer.py
- src/frontend/src/app/components/home/home.component.ts
- src/frontend/src/app/components/layout/header/header.component.html
- src/frontend/src/app/components/profile/profile-update/profile-update.component.html
- src/frontend/src/app/components/profile/profile-update/profile-update.component.ts
- src/frontend/src/app/components/profile/profile/profile.component.html
- src/frontend/src/app/models/user.ts
- src/frontend/src/app/services/tag.service.spec.ts
- src/frontend/src/app/services/tag.service.ts
- src/frontend/src/environments/environment.prod.ts
- src/frontend/src/environments/environment.ts
This PR does a couple things:
1. Allows child users to update their interests on the frontend
2. Orders event listings with child interests first
Preview:
This PR will also close #196
> Add child interests

- SETUP-PROD.md
Real small update to the prod setup doc for setting up the secret keys. Everything appears to be working well after that!
> Add secret key steps to prod setup
